name: sarscov2_290k
channels:
  - conda-forge
dependencies:
  - python=3.10.10
  - numpy==1.24
  - pandas
  - matplotlib
  - scikit-learn
  - ipywidgets
  - ipykernel
  - seaborn
  - tqdm
  - cudatoolkit
  - statsmodels
  - pip:
    - pygam==0.9.0
    - scienceplots
    - jax==0.4.10
    - jaxlib==0.4.10+cuda11.cudnn86